# GHC 9.2.5
resolver: lts-20.0

packages:
- .

extra-deps:
# Temporarily relying on test versions of 'hpack' and 'pantry':
# Modified hpack
- git: https://github.com/sol/hpack
  commit: beef09faa9fac949be56766a6de788d4cb948115
# Modified pantry in branch 'fix-hpack530'
- git: https://github.com/commercialhaskell/pantry/
  commit: ec2048adfaf785e94a8744239bdb9878a99751a6
# - pantry-0.8.0@sha256:351a9103c0b1dd78f6b8f243ca4fc6a6952d5ba00f72032b831e5ee0e61dce0f,4099
- rio-prettyprint-0.1.4.0@sha256:1f8eb3ead0ef33d3736d53e1de5e9b2c91a0c207cdca23321bd74c401e85f23a,1301
- fsnotify-0.4.1.0@sha256:44540beabea36aeeef930aa4d5f28091d431904bc9923b6ac4d358831c651235,2854

drop-packages:
# See https://github.com/commercialhaskell/stack/pull/4712
- cabal-install

docker:
  enable: false
  repo: fpco/alpine-haskell-stack:9.2.5

nix:
  # --nix on the command-line to enable.
  packages:
  - zlib
  - unzip

flags:
  stack:
    developer-mode: true

ghc-options:
  "$locals": -fhide-source-paths
